# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: techdecaf/ci:latest
# image: node:8.11-alpine

variables:
  DECAF_VAR: "value"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  - .npmrc

# run in order.
stages:
  - test
  - deploy

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
# you can specify a alias to access the locally attached service.
#  - redis:latest
#    alias: redis
#  - mongo:3.4

# runs before each job
before_script:
  - echo this runs before each job

test:
  stage: test
  script:
    - curl -s "$DECAF_URL/keys/npm/npmrc?jwt=$DECAF_TOKEN" > .npmrc
    - npm install
    - npm run ci
  coverage: /All files\s*\|\s*([\d\.]+)/
  cache:
    paths:
    - node_modules/
    - .npmrc

# deployment
deploy:
  stage: deploy
  script:
    - npm run deploy --unsafe-perm
  # an array of permitted branches
  only:
    - master
