# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
# image: golang:1.13-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - $CI_PROJECT_DIR/dist

stages:
  - test
  - deploy

test:
  image: golang:1.13-alpine
  stage: test
  script:
    - apk add git
    - go run . -h
    - go run . install https://github.com/techdecaf/cgen-template

deploy:
  image: techdecaf/ci:1.3.0
  stage: deploy
  script:
    - eval $(tasks run login --log false)
    - tasks run publish
  only:
    - master
