# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

# image: golang:1.13-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - $CI_PROJECT_DIR/dist

stages: [test, deploy]

test:
  image: golang:1.13-alpine
  stage: test
  script:
    - apk add git
    - go run . -h
    - go run . install https://github.com/techdecaf/cgen-template

deploy:
  image: techdecaf/ci:v1.3.0
  stage: deploy
  script:
    - eval $(tasks run login --log false)
    - tasks run publish
  only:
    - master
