# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

# image: golang:1.13-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths: [$CI_PROJECT_DIR/dist]

before_script:
  - apk add git curl
  - sh -c "$(curl -fsSL https://raw.github.com/techdecaf/tasks/master/install.sh)"

stages: [test, deploy]

test:
  image: golang:1.13-alpine
  stage: test
  script:
    - tasks run integration
    - go run . help
    - go run . install https://github.com/techdecaf/cgen-template.git
    - go run . list

deploy:
  image: techdecaf/ci:v1.3.0
  stage: deploy
  script:
    - eval $(tasks run login -s)
    - tasks run build publish
  only: [master]
  except: { changes: ["*.md"] }
