# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

image: golang:1.13-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths: [$CI_PROJECT_DIR/dist]

before_script:
  - apk add git curl
  - sh -c "$(curl -fsSL https://raw.github.com/techdecaf/tasks/master/install.sh)"

stages: [test, build, deploy]

test:
  stage: test
  script: [tasks run test]
  only: [branches, tags]
  except: [master]

build:
  stage: build
  script: [tasks run build]
  artifacts:
    paths: [build/]
    expire_in: 1 week
  only: [/^v\d+.\d+.\d+/]
  except: [branches]

deploy:
  stage: deploy
  script:
    - eval $(tasks run login -s)
    - tasks run publish
  only: [/^v\d+.\d+.\d+$/]
  except: [branches]
  # except: { changes: ["*.md"] }
