# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

image: golang:1.13-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths: [$CI_PROJECT_DIR/dist]

before_script:
  - apk add git curl
  - sh -c "$(curl -fsSL https://raw.github.com/techdecaf/tasks/master/install.sh)"
  - eval $(tasks run login -s)

stages: [test, upload, publish]

test:
  stage: test
  script: [tasks run coverage test]
  artifacts:
    paths: [build/]
    expire_in: 1 week
  only: [branches, tags]
  except: [master]

upload:
  stage: upload
  image: docker pull techdecaf/ci:latest
  script: [tasks run upload]
  only: [/^v\d+.\d+.\d+/]
  except: [branches]

publish:
  stage: publish
  image: docker pull techdecaf/ci:latest
  script: [tasks run publish]
  only: [/^v\d+.\d+.\d+$/]
  except: [branches]
