options:
  log: true # debug, info, error, silent

variables:
  CI_PROJECT_NAME: "{{EXEC `echo ${PWD##*/}`}}"
  CI_COMMIT_TAG: "{{TRY `git describe --tags --always --dirty --abbrev=0`}}"
  CI_COMMIT_REF_NAME: "{{TRY `git rev-parse --abbrev-ref HEAD`}}"
  CI_COMMIT_SHA: "{{TRY `git rev-parse HEAD`}}"
  S3_BUCKET: github.techdecaf.io
  DOWNLOAD_URI: http://{{.S3_BUCKET}}/{{.CI_PROJECT_NAME}}/latest

tasks:
  default:
    description: is the task that runs when no tasks have been specified. `tasks run` == `tasks run default`
    commands: [tasks list]

  dependencies:
    description: install all required dependencies
    commands: [go get, go install]

  build:
    description: compile window, linux, osx x64
    pre: [clean, dependencies]
    variables:
      flags: build -ldflags "-X main.VERSION={{.CI_COMMIT_TAG}}"
    commands:
      - GOOS=darwin go {{.flags}} -o dist/darwin/{{.CI_PROJECT_NAME}} -v
      - GOOS=linux go {{.flags}} -o dist/linux/{{.CI_PROJECT_NAME}} -v
      - GOOS=windows go {{.flags}} -o dist/windows/{{.CI_PROJECT_NAME}}.exe -v

  clean:
    description: removes all files listed in .gitignore
    commands: ["rm -rf dist"]

  install:
    description: installs locally to /usr/local/bin
    commands:
      - "chmod +x dist/{{OS}}/{{.CI_PROJECT_NAME}}"
      - "cp dist/{{OS}}/{{.CI_PROJECT_NAME}} /usr/local/bin"

  publish:
    description: moves compiled files to /usr/local/bin/
    commands:
      - "aws s3 sync dist s3://{{.S3_BUCKET}}/{{.CI_PROJECT_NAME}}/{{.CI_COMMIT_TAG}}"
      - "aws s3 sync dist s3://{{.S3_BUCKET}}/{{.CI_PROJECT_NAME}}/latest"

  login:
    description: checkout temporary aws access keys
    commands:
      - curl -s "$DECAF_URL/keys/aws/set/env/linux/website-update?jwt=$DECAF_TOKEN"

  docs:
    description: auto generate documentation
    commands:
      # expand the file, and pipe to write, if no errors default to the string "success"
      - "echo {{ExpandFile `docs/README.md` | WriteFile `README.md` | default `docs updated`}}"
